server:
  port: 8080

spring:
  application:
    name: api-gateway
#  cloud:
#    gateway:
#      routes:
#        - id: auth-service
#          uri: lb://auth-service
#          predicates:
#            - Path=/auth/**
#          filters:
#            - RewritePath=/auth/(?<path>.*), /$\{path}
#        - id: forum-service
#          uri: lb://forum-service
#          predicates:
#            - Path=/forum/**
#          filters:
#            - AuthFilters
          
management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true

jwt.secret: bimatkhongbatmi

eureka:
  instance:
    preferIpAddress: true 
  client:
    registerWithEureka: true
    fetchRegistry : true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/