spring:
  application:
    name: eureka-server
  boot:
    admin:
      context-path: /admin
  cloud:
    config:
      enabled: false
server:
  port: 8761
eureka:
  instance:
    hostname: eurekaserver
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 5
    enableSelfPreservation: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

