eureka:
  instance:
    preferIpAddress: true 
  client:
    registerWithEureka: true
    fetchRegistry : true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8088
  
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/db04
    username: root
    password: Zaq12wsx1234
    hikari:
      data-source-properties:
        useUnicode: true
        characterEncoding: UTF-8
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        
management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true


