name: CI
on: push
jobs:
    show-info:
        runs-on: ubuntu-latest
        steps:
        - name: Display Info of new commit
          run: |
            echo "Runner Machine Name : $(hostname)"
            echo "Operating System: $(uname)"
            echo "Commit SHA: $GITHUB_SHA"
            echo "Git Ref: $GITHUB_REF"
